flyapp/urls.py
# baby urls

from django.urls import path
from . import views

app_name = 'flyapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('meetTheTeam/', views.meetTheTeam, name='meetTheTeam'),
    path('register_customer/', views.register_customer, name='register_customer'),
    path('login/', views.login_customer, name='login_customer'),
    path('logout/', views.logout_customer, name='logout_customer'),    
]

flyaway/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flyapp.urls')),
]

flyapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  phone = models.CharField(max_length=20, blank=True)
  address1 = models.CharField(max_length=100, blank=True)
  address2 = models.CharField(max_length=100, blank=True)
  city = models.CharField(max_length=100, blank=True)
  postcode = models.CharField(max_length=100, blank=True)

  def __str__(self):
    return f"{self.user.username} has firstname: {self.user.first_name} and email: {self.user.email}"

def create_profile(sender, instance, created, **kwargs):
  if created:
    user_profile = Profile(user=instance)
    user_profile.save()

post_save.connect(create_profile, sender=User)

flyapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
  email = forms.EmailField()
  first_name = forms.CharField(max_length=50)
  last_name = forms.CharField(max_length=50)

  class Meta:
      model = User
      fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

flyapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import *
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import *
# Create your views here.

def home(request):
    return render(request, 'flyapp/home.html')

def profile(request):
    if User.is_authenticated:
        return render(request, 'flyapp/profile.html')
    else:
        return redirect('flyapp:login_customer')

def meetTheTeam(request):
    return render(request, 'flyapp/meetTheTeam.html')

def register_customer(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Registration complete"))
            return redirect('flyapp:home')
    else:
        form = RegisterUserForm()
    
    return render(request, 'flyapp/register_customer.html', {'form':form})

def login_customer(request):
    if request.method =="POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request,"You have been logged in ... quack! quack!")
            return redirect('flyapp:home')
        else:
            messages.success(request,("There was an error logging in, Try Again..."))
            return redirect('flyapp:login_customer')
    else:
        return render(request, 'flyapp/login.html', {})

def logout_customer(request):
    logout(request)
    messages.success(request, ("You have been logged out"))
    return redirect('flyapp:home') 

flyapp/templates/flyapp/footer.html
{% load static %}

<footer>
  <div class="bar">
    <label class="switch">
      <input type="checkbox" id="darkModeToggle">
      <span class="slider round"></span>
    </label>
  </div>
  <script src="{% static 'js/darkMode.js' %}"></script>
</footer>
</html>

flyapp/templates/flyapp/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/mainStyle.css' %}">
  <link rel="icon" href="{% static 'img/logo.png' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Monoton&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

  <title>Fly App</title>
</head>
<header>
  <div class="bar">
    <div class="logo-title">
      <div class="logo">
        <img src="{% static 'img/logo.png' %}" id="logo" alt="FlyAway">
      </div>
      <div class="title">
        <h1>Fly Away</h1>
      </div>
    </div>
    <div class="nav">
      <nav>
        <ul class="flex-container">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'flyapp:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'flyapp:meetTheTeam' %}">Meet the Team</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'flyapp:profile' %}">Profile</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="{% url 'flyapp:logout_customer' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'flyapp:login_customer' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'flyapp:register_customer' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</header>

flyapp/templates/flyapp/home.html
{% include 'flyapp/header.html' %}

<div class="container">
  <h1>Home</h1>
</div>

{% include 'flyapp/footer.html' %}

flyapp/templates/flyapp/login.html
{% include 'flyapp/header.html' %}

<div class="container">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    <label for="username">Username:</label><br>
    <input type="text" id="username" name="username" placeholder="username">
    <br>
    <label for="password">Password:</label><br>
    <input type="password" id="password" name="password" placeholder="password">  
    <br><br>
    <div class="submit-button">
      <input type="submit" value="Submit">
    </div>
  </form>
</div>

  {% include 'flyapp/footer.html' %}

flyapp/templates/flyapp/meetTheTeam.html
{% include 'flyapp/header.html' %}

<div class="container">
  <h1>Meet the Team</h1>
</div>

{% include 'flyapp/footer.html' %}

flyapp/templates/flyapp/profile.html
{% include 'flyapp/header.html' %}
{% load static %}

  {% if user.is_authenticated %}
    <div id="account" class="content">
      <div class="header-container" style="text-align: center;">
        <svg xmlns="http://www.w3.org/2000/svg" height="40" width="50" viewBox="0 0 448 512">
          <path fill="rgb(251,179,4)" d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464H398.7c-8.9-63.3-63.3-112-129-112H178.3c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3z"/>
        </svg>
        <h1 id="headings">My Profile</h1>
      </div>
      <div class="accountInfo">
        <div class="iconContainer">
          <img src="{% static 'img/logo.png' %}" alt="Profile Picture" id="profilePicture" draggable="false">
          <svg xmlns="http://www.w3.org/2000/svg" height="50" width="50" viewBox="0 0 512 512" id="editIcon" onclick="showEditForm()">
            <path fill="rgb(251,179,4)" d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.7 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160V416c0 53 43 96 96 96H352c53 0 96-43 96-96V320c0-17.7-14.3-32-32-32s-32 14.3-32 32v96c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h96c17.7 0 32-14.3 32-32s-14.3-32-32-32H96z"/>
          </svg>
          <div id="editForm" style="display: none;">
            <form method="post">
              <!-- CSRF token for Django forms -->
              {% csrf_token %}
              <!-- Form fields for account information go here -->
              <input type="submit" value="Save Changes">
            </form>
          </div>
        </div>
        <div class="accountDetails" style="margin: 4rem 0 0 1rem ;">
          <h1>{{ user.username }}</h1>
        </div>
      </div>  
    </div>
  {% else %}
    <h2>You are not logged in.</h2>
  {% endif %}


{% include 'flyapp/footer.html' %}

flyapp/templates/flyapp/register_customer.html
{% include 'flyapp/header.html' %}

{% if form.errors %}
<p>There was an error with your form</p>

{% endif %}

<h1>Register</h1>
<form action="{% url 'flyapp:register_customer' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>

{% include 'flyapp/footer.html' %}